import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import MainNav from "../../components/main-nav";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Arturo Marte",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {" "}
        {/* 👈 Insert viewport meta tag here */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <MainNav />
        {children}
      </body>
    </html>
  );
}
